### ISSUE TITLE
Can we build this minecraft-recode to android target?

### ISSUE THREAD

**Issue by codingwatching** [mikex86/minecraft-recode#2]
Hi @mikex86 
I just found this project and it is awesome project
Can we build this game for android, as I see LibGDX support android platform
Thank you so much!

**Comment by mikex86** [comment]
It should be possible to build the project for Android by creating a launcher for Android. It should be fairly straightforward. See ./desktop for reference how a launcher is implemented. Ignore CreateSoundsTxt.java, which is a debug utility only used for creating the sounds.txt resource.

There is explicit controller code for touch screens, which should still work. See EntityPlayerSP.MobilePlayerController
However Android hasn't been explicitly supported for some time and things could have broken since then.
